version: "3.7"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8081:80"
        volumes:
            - ./src:/var/www/html:rw
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        links:
            - ref-php
        depends_on:
            - ref-php
        networks:
            - u-online
    ref-php:
        build: ./docker/php
        container_name: ref-php
        volumes:
            - ./src:/var/www/html:rw
            - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            DB_DRIVER: $DB_DRIVER
            DB_HOST: $DB_HOST
            DB_PORT: $DB_PORT
            DB_NAME: $DB_NAME
            DB_NAME_GLOBAL: $DB_NAME_GLOBAL
            DB_NAME_SHARD: $DB_NAME_SHARD
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        links:
            - ref-db
        networks:
            - u-online
    ref-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ref-phpmyadmin
        ports:
            - "8091:80"
        links:
            - ref-db
        environment:
            PMA_HOST: ref-db
        networks:
            - u-online
    ref-db:
#        image: mysql:8.0.20
        image: mysql:5.7.17
        container_name: ref-db
        ports:
            - "33061:3306"
        volumes:
            - ./docker/mysql-init:/docker-entrypoint-initdb.d:rw
            - ./docker/mysql/:/var/lib/mysql/:rw
#            - ./docker/mysql-init/mysqld.cnf:/etc/mysql/mysqld.cnf
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/mysql-init.sql
        environment:
            MYSQL_ROOT_HOST: $ROOT_HOST
            MYSQL_DATABASE_GLOBAL: $DB_NAME_GLOBAL
            MYSQL_DATABASE_SHARD: $DB_NAME_SHARD
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_ALLOW_EMPTY_PASSWORD: $DB_ALLOW_EMPTY_PASSWORD
        restart: always
        networks:
            - u-online
#Docker Networks
networks:
    u-online:
        driver: bridge
