doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            proton_mail_global:
                url: '%env(resolve:DATABASE_GLOBAL_URL)%'
            proton_mail_shard:
                url: '%env(resolve:DATABASE_SHARD_URL)%'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Main:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            proton_mail_global:
                connection: proton_mail_global
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Global:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Global'
                        prefix: 'App\Entity\Global'
                        alias: Global
            proton_mail_shard:
                connection: proton_mail_shard
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Shard:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Shard'
                        prefix: 'App\Entity\Shard'
                        alias: Shard
#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
#
#when@prod:
#    doctrine:
#        orm:
#            auto_generate_proxy_classes: false
#            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#            query_cache_driver:
#                type: pool
#                pool: doctrine.system_cache_pool
#            result_cache_driver:
#                type: pool
#                pool: doctrine.result_cache_pool
#
#    framework:
#        cache:
#            pools:
#                doctrine.result_cache_pool:
#                    adapter: cache.app
#                doctrine.system_cache_pool:
#                    adapter: cache.system
